"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createServerSupabaseClient} from "@/lib/supabase-server";
const str=(f:FormData,k:string)=>String(f.get(k)??"").trim();const num=(f:FormData,k:string)=>Number(f.get(k)??0);const nullable=(f:FormData,k:string)=>str(f,k)||null;
export async function createEmployee(f:FormData){const s=await createServerSupabaseClient();const {data,error}=await s.rpc("fn_create_employee",{p_full_name:str(f,"full_name"),p_work_email:str(f,"work_email"),p_department:str(f,"department"),p_job_title:str(f,"job_title"),p_employment_type:str(f,"employment_type")||"employee",p_hire_date:nullable(f,"hire_date"),p_pay_frequency:str(f,"pay_frequency")||"monthly",p_base_salary:num(f,"base_salary")});if(error)throw new Error(error.message);revalidatePath("/payroll/employees");redirect(`/payroll/employees/${data}`)}
export async function updateEmployee(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_update_employee",{p_employee_id:id,p_full_name:str(f,"full_name"),p_work_email:str(f,"work_email"),p_department:str(f,"department"),p_job_title:str(f,"job_title"),p_employment_type:str(f,"employment_type"),p_hire_date:nullable(f,"hire_date"),p_pay_frequency:str(f,"pay_frequency"),p_pay_basis:str(f,"pay_basis"),p_hourly_rate:num(f,"hourly_rate"),p_overtime_multiplier:num(f,"overtime_multiplier")||1.5});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`);revalidatePath("/payroll/employees")}
export async function setEmployeeStatus(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_set_employee_status",{p_employee_id:id,p_status:str(f,"status"),p_effective_date:nullable(f,"effective_date"),p_reason:str(f,"reason")});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`);revalidatePath("/payroll/employees")}
export async function changeEmployeeSalary(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_change_employee_salary",{p_employee_id:id,p_effective_from:str(f,"effective_from"),p_base_salary:num(f,"base_salary"),p_pay_frequency:str(f,"pay_frequency"),p_pay_basis:str(f,"pay_basis"),p_hourly_rate:num(f,"hourly_rate"),p_overtime_multiplier:num(f,"overtime_multiplier")||1.5,p_reason:str(f,"reason")});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`)}
export async function addCompensationComponent(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_add_employee_component",{p_employee_id:id,p_component_name:str(f,"component_name"),p_category:str(f,"component_category"),p_type:str(f,"component_type"),p_calculation_type:str(f,"calculation_type"),p_value:num(f,"value"),p_recurring:f.get("recurring")!==null});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`)}
export async function addCommissionRule(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_add_commission_rule",{p_employee_id:id,p_rule_name:str(f,"rule_name"),p_method:str(f,"calculation_method"),p_rate:num(f,"rate"),p_threshold:num(f,"threshold"),p_effective_from:nullable(f,"effective_from"),p_effective_to:nullable(f,"effective_to")});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`)}
export async function recordTimeEntry(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_record_time_entry",{p_employee_id:id,p_work_date:str(f,"work_date"),p_regular_hours:num(f,"regular_hours"),p_overtime_hours:num(f,"overtime_hours"),p_absence_hours:num(f,"absence_hours"),p_note:str(f,"note")});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`)}
export async function recordCommissionInput(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"employee_id");const {error}=await s.rpc("fn_record_commission_input",{p_employee_id:id,p_period_start:str(f,"period_start"),p_period_end:str(f,"period_end"),p_sales_amount:num(f,"sales_amount"),p_units:num(f,"units"),p_note:str(f,"note")});if(error)throw new Error(error.message);revalidatePath(`/payroll/employees/${id}`)}
export async function createPayrollRun(f:FormData){const s=await createServerSupabaseClient();const {data,error}=await s.rpc("fn_create_payroll_run",{p_period_start:str(f,"period_start"),p_period_end:str(f,"period_end"),p_pay_date:str(f,"pay_date"),p_pay_frequency:str(f,"pay_frequency")||"monthly"});if(error)throw new Error(error.message);revalidatePath("/payroll/runs");redirect(`/payroll/runs/${data}`)}
export async function addPayrollAdjustment(f:FormData){const s=await createServerSupabaseClient(),run=str(f,"run_id");const {error}=await s.rpc("fn_add_payroll_adjustment",{p_run_item_id:str(f,"run_item_id"),p_name:str(f,"adjustment_name"),p_category:str(f,"adjustment_category"),p_type:str(f,"adjustment_type"),p_amount:num(f,"amount"),p_note:str(f,"note")});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${run}`)}
export async function submitPayrollForApproval(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"run_id");const {error}=await s.rpc("fn_submit_payroll_for_approval",{p_run_id:id});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${id}`);revalidatePath("/payroll/runs")}
export async function approvePayrollRun(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"run_id");const {error}=await s.rpc("fn_approve_payroll_run",{p_run_id:id});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${id}`);revalidatePath("/payroll/runs")}
export async function generatePayrollPayments(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"run_id");const {error}=await s.rpc("fn_generate_payroll_payments",{p_run_id:id});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${id}`);revalidatePath("/payroll/runs");revalidatePath("/transfers")}
export async function reopenPayrollRun(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"run_id");const {error}=await s.rpc("fn_reopen_payroll_run",{p_run_id:id,p_reason:str(f,"reason")});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${id}`);revalidatePath("/payroll/runs")}
export async function reversePayrollRun(f:FormData){const s=await createServerSupabaseClient(),id=str(f,"run_id");const {error}=await s.rpc("fn_reverse_payroll_run",{p_run_id:id,p_reason:str(f,"reason")});if(error)throw new Error(error.message);revalidatePath(`/payroll/runs/${id}`);revalidatePath("/payroll/runs");revalidatePath("/transfers")}
