import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import ProcurementApprovalControls from "@/components/ProcurementApprovalControls";
import { createDisbursementFromProcurement } from "@/app/actions/disbursements";
import { createServerSupabaseClient } from "@/lib/supabase-server";

const ngn = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2 });
export default async function ProcurementDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect(`/login?next=${encodeURIComponent(`/procurement/${id}`)}`);
  const { data: request } = await supabase.from("procurement_requests").select("*").eq("id", id).single(); if (!request) notFound();
  const { data: items } = await supabase.from("procurement_request_items").select("*").eq("request_id", id).order("line_no");
  const ids = [request.requested_by,request.verified_by,request.finance_reviewed_by,request.final_approved_by].filter(Boolean);
  const { data: people } = ids.length ? await supabase.from("profiles").select("id,full_name").in("id",ids) : { data: [] };
  const name = (uid:string|null) => people?.find((p)=>p.id===uid)?.full_name;
  const { data: member } = await supabase.from("procurement_members").select("workflow_role").eq("user_id",user.id).maybeSingle();
  const { data: linkedTransfer } = await supabase.from("transfers").select("id,transaction_no,status,amount_transferred").eq("procurement_request_id",id).maybeSingle();
  const canCreateDisbursement = request.status === "approved" && ["finance_officer","final_approver"].includes(member?.workflow_role ?? "");
  return <main className="min-h-screen bg-[#f5f7f5] px-5 py-8 text-[#152019]"><div className="mx-auto max-w-5xl"><Link href="/procurement" className="text-sm font-semibold text-[#006b3c] hover:underline">← Requests</Link><article className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm">
    <header className="bg-[#063d28] p-7 text-white"><p className="text-sm font-bold uppercase tracking-wider text-[#FDB515]">ZARIKS™ Cashflow Control</p><div className="mt-2 flex flex-col justify-between gap-3 sm:flex-row"><div><h1 className="text-3xl font-bold">Money / Procurement Request</h1><p className="mt-1 text-green-100">{request.request_no}</p></div><div className="text-left sm:text-right"><p className="text-sm text-green-100">TOTAL</p><p className="text-3xl font-bold text-[#FDB515]">{ngn.format(Number(request.total_amount))}</p></div></div></header>
    <div className="space-y-8 p-7"><section className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Date" value={request.request_date}/><Info label="Type" value={String(request.request_type).replaceAll("_"," ")}/><Info label="From Whom" value={request.from_whom||"—"}/><Info label="To Whom" value={request.to_whom||"—"}/><Info label="Department" value={request.department||"—"}/><Info label="Required By" value={request.required_by||"—"}/><Info label="Status" value={String(request.status).replaceAll("_"," ")}/><Info label="Currency" value="Nigerian Naira (NGN)"/></section>
    <section><h2 className="text-sm font-bold uppercase tracking-wider text-[#006b3c]">For What? / Purpose</h2><p className="mt-2 text-lg font-semibold">{request.purpose}</p>{request.justification&&<p className="mt-2 text-gray-600">{request.justification}</p>}</section>
    <section><h2 className="mb-3 text-sm font-bold uppercase tracking-wider text-[#006b3c]">Items</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f3f0e6]"><tr><th className="p-3 text-left">#</th><th className="p-3 text-left">Item</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">Qty</th><th className="p-3 text-left">Unit</th><th className="p-3 text-right">Unit Cost</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{(items??[]).map((x)=><tr key={x.id} className="border-b"><td className="p-3">{x.line_no}</td><td className="p-3 font-semibold">{x.item_name}</td><td className="p-3">{x.description||"—"}</td><td className="p-3 text-right">{x.quantity}</td><td className="p-3">{x.unit||"—"}</td><td className="p-3 text-right">{ngn.format(Number(x.unit_cost))}</td><td className="p-3 text-right font-bold">{ngn.format(Number(x.amount))}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 border-t pt-6 md:grid-cols-4"><Sign label="REQUESTED BY" value={name(request.requested_by)||"Requester"} date={request.created_at}/><Sign label="VERIFIED BY" value={name(request.verified_by)||"Dibia Emmanuel — Pending"} date={request.verified_at}/><Sign label="FINANCE REVIEWED BY" value={name(request.finance_reviewed_by)||"Sr. Bola Daramola — Pending"} date={request.finance_reviewed_at}/><Sign label="FINAL APPROVAL" value={name(request.final_approved_by)||"Gabriel Ayayia — Pending"} date={request.final_approved_at}/></section>
    <ProcurementApprovalControls requestId={id} status={request.status} workflowRole={member?.workflow_role??null}/>
    {linkedTransfer ? <section className="rounded-xl border border-green-200 bg-green-50 p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#006b3c]">Linked Payment / Disbursement</p><h2 className="mt-2 text-xl font-bold">{linkedTransfer.transaction_no}</h2><p className="mt-1 text-sm text-gray-600">This payment record is permanently linked to {request.request_no}. Current payment status: <strong className="capitalize">{String(linkedTransfer.status).replaceAll("_"," ")}</strong>.</p><Link href={`/transfers/${linkedTransfer.id}`} className="mt-4 inline-block rounded-lg bg-[#006b3c] px-5 py-3 font-bold text-white">Open Payment / Disbursement →</Link></section>
    : canCreateDisbursement ? <section className="rounded-xl border-2 border-[#d8c77a] bg-[#fffdf5] p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#006b3c]">Final approval complete · Payment stage</p><h2 className="mt-2 text-xl font-bold">Ready for Payment / Disbursement</h2><p className="mt-2 text-sm text-gray-600">Final approval authorizes this expenditure but does not mean money has moved. Create the linked payment record below; Finance must then record the actual bank payment and evidence.</p><form action={createDisbursementFromProcurement} className="mt-4"><input type="hidden" name="request_id" value={id}/><button className="rounded-lg bg-[#FDB515] px-6 py-3 font-bold text-[#172016]">Record Payment / Disbursement</button></form></section> : null}
    </div></article></div></main>;
}
function Info({label,value}:{label:string,value:string}){return <div><p className="text-xs font-bold uppercase tracking-wider text-gray-500">{label}</p><p className="mt-1 font-semibold capitalize">{value}</p></div>}
function Sign({label,value,date}:{label:string,value:string,date:string|null}){return <div className="rounded-xl border p-4"><p className="text-xs font-bold tracking-wider text-[#006b3c]">{label}</p><p className="mt-3 font-bold">{value}</p><p className="mt-1 text-xs text-gray-500">{date?new Date(date).toLocaleString("en-NG"):"Awaiting action"}</p></div>}
