"use client";

import Link from "next/link";
import Image from "next/image";
import { logout } from "@/app/actions/auth";

function money(amount:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(amount)}

export default function DashboardClient({user}:{user:{email:string;fullName:string;role:string}}){
 const awaiting=0,total=0,awaitingCertification=0,certified=0;
 return <main className="min-h-screen bg-[#f5f7f5] text-[#152019]">
  <header className="bg-[#063d28] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><div className="flex items-center gap-4"><Image src="/zariks-logo.png" alt="ZARIKS Logo" width={56} height={56} priority className="h-14 w-14 rounded-xl object-cover shadow-sm"/><div><h1 className="text-xl font-bold tracking-wide">ZARIKS</h1><p className="text-xs text-green-100">Financial Control &amp; Accountability</p></div></div><div className="text-right"><p className="text-sm font-semibold">{user.fullName}</p><p className="text-xs capitalize text-green-100">{user.role.replaceAll("_"," ")}</p></div></div></header>
  <nav className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-6 overflow-x-auto px-6 py-4 text-sm font-medium md:px-8"><Link href="/" className="whitespace-nowrap font-semibold text-[#006b3c]">Dashboard</Link><Link href="/procurement" className="whitespace-nowrap hover:text-[#006b3c]">Requests</Link><Link href="/payroll" className="whitespace-nowrap font-semibold text-[#006b3c]">Payroll &amp; Schedules</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Payments &amp; Transfers</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Approvals</Link><Link href="/mediatrix" className="whitespace-nowrap hover:text-[#006b3c]">Mediatrix</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Bello Foods</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Retirement</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Reports</Link><div className="ml-auto whitespace-nowrap"><form action={logout}><button type="submit" className="font-semibold text-red-700">Sign out</button></form></div></div></nav>
  <section className="mx-auto max-w-7xl px-6 py-8 md:px-8">
   <div className="mb-8 flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="mb-1 text-sm font-semibold uppercase tracking-wider text-[#006b3c]">Financial Control</p><h2 className="text-3xl font-bold">ZARIKS Financial Control Dashboard</h2><p className="mt-2 text-sm text-gray-500">Request, verify, approve, schedule, pay, certify, retire and reconcile ZARIKS funds.</p></div><Link href="/procurement/new" className="inline-flex items-center justify-center rounded-lg bg-[#006b3c] px-6 py-3 font-bold text-white shadow-sm">+ New Financial Request</Link></div>
   <div className="mb-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Requests Awaiting Action" value={String(awaiting)}/><Metric label="Approved / Disbursed Value" value={money(total)}/><Metric label="Payments Awaiting Certification" value={String(awaitingCertification)}/><Metric label="Certified / Closed" value={String(certified)}/></div>
   <div className="mb-8 rounded-xl border-2 border-[#d8c77a] bg-[#fffdf5] p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-[#006b3c]">Start here · Spending authorization</p><h3 className="mt-1 text-xl font-bold">Financial Requests</h3><p className="mt-1 max-w-2xl text-sm text-gray-600">Create procurement, salary, commission, bonus, allowance and other financial requests. Approval authorizes the obligation; payment records the actual movement of money.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-green-100 px-3 py-1">1 Request</span><span className="rounded-full bg-green-100 px-3 py-1">2 Verify</span><span className="rounded-full bg-green-100 px-3 py-1">3 Finance Review</span><span className="rounded-full bg-green-100 px-3 py-1">4 Final Approval</span></div></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row"><Link href="/procurement" className="rounded-lg border border-[#006b3c] px-5 py-3 text-center font-bold text-[#006b3c]">View Requests</Link><Link href="/procurement/new" className="rounded-lg bg-[#006b3c] px-5 py-3 text-center font-bold text-white">Create Request</Link></div></div></div>
   <div className="mb-8 grid gap-5 md:grid-cols-4"><QuickAction title="Requests" description="Create and track financial authorization before money moves." href="/procurement" action="Open requests →"/><QuickAction title="Payroll & Scheduled Payments" description="See approved recurring salaries, commissions and allowances due this week or month and generate the next payment." href="/payroll" action="Open payroll →"/><QuickAction title="Payments & Transfers" description="Process actual disbursements created after final approval or from an approved schedule." href="/transfers" action="View payments →"/><QuickAction title="Recipient Confirmation" description="Review payments awaiting receipt or certification." href="/mediatrix" action="Open confirmations →"/></div>
   <div className="mb-8 rounded-xl border bg-white p-6 shadow-sm"><div className="mb-5"><h3 className="text-lg font-bold">ZARIKS Financial Control Flow</h3><p className="text-sm text-gray-500">One-time requests proceed to payment after approval. Approved recurring requests become schedules and generate future payment records when due.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><WorkflowStep number="1" label="Request"/><WorkflowStep number="2" label="Verify"/><WorkflowStep number="3" label="Finance Review"/><WorkflowStep number="4" label="Final Approval"/><WorkflowStep number="5" label="Schedule / Pay"/><WorkflowStep number="6" label="Receipt / Certify"/><WorkflowStep number="7" label="Retire"/><WorkflowStep number="8" label="Close"/></div></div>
   <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-5"><div><h3 className="font-bold">Recent Payments &amp; Fund Transfers</h3><p className="text-sm text-gray-500">Actual money movements will appear here after approved requests or scheduled obligations are paid.</p></div><Link href="/transfers" className="text-sm font-semibold text-[#006b3c]">View all →</Link></div><div className="px-6 py-10 text-center text-sm text-gray-500">No payments or fund transfers recorded yet.</div></div>
  </section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function WorkflowStep({number,label}:{number:string;label:string}){return <div className="rounded-lg border border-green-100 bg-green-50 p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-full bg-[#006b3c] text-xs font-bold text-white">{number}</div><p className="text-sm font-semibold">{label}</p></div>}
function QuickAction({title,description,href,action}:{title:string;description:string;href:string;action:string}){return <div className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm text-gray-500">{description}</p><Link href={href} className="mt-4 inline-block text-sm font-semibold text-[#006b3c]">{action}</Link></div>}
