"use client";

import Link from "next/link";
import Image from "next/image";
import { logout } from "@/app/actions/auth";

type Transfer = { id:string; recipient:string; purpose:string; amount:number; status:string; date:string };
const initialTransfers: Transfer[] = [
  { id:"ZARI-TRF-2026-000001", recipient:"Mediatrix Consulting Services Ltd", purpose:"Production & Processing", amount:1250000, status:"Awaiting Receipt", date:"12 Aug 2026" },
  { id:"ZARI-TRF-2026-000002", recipient:"Mediatrix Consulting Services Ltd", purpose:"Packaging Materials", amount:480000, status:"Approved", date:"11 Aug 2026" },
  { id:"ZARI-TRF-2026-000003", recipient:"Mediatrix Consulting Services Ltd", purpose:"Raw Materials", amount:735000, status:"Certified", date:"10 Aug 2026" },
];
function money(amount:number){return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(amount)}

export default function DashboardClient({user}:{user:{email:string;fullName:string;role:string}}){
 const total=initialTransfers.reduce((s,t)=>s+t.amount,0);
 const pending=initialTransfers.filter(t=>["Awaiting Receipt","Approved","Submitted"].includes(t.status)).length;
 const certified=initialTransfers.filter(t=>t.status==="Certified").length;
 return <main className="min-h-screen bg-[#f5f7f5] text-[#152019]">
  <header className="bg-[#063d28] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><div className="flex items-center gap-4"><Image src="/zariks-logo.png" alt="ZARIKS Logo" width={56} height={56} priority className="h-14 w-14 rounded-xl object-cover shadow-sm"/><div><h1 className="text-xl font-bold tracking-wide">ZARIKS</h1><p className="text-xs text-green-100">Transfer Control &amp; Accountability</p></div></div><div className="text-right"><p className="text-sm font-semibold">{user.fullName}</p><p className="text-xs capitalize text-green-100">{user.role.replaceAll("_"," ")}</p></div></div></header>
  <nav className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center gap-6 overflow-x-auto px-6 py-4 text-sm font-medium md:gap-8 md:px-8">
   <Link href="/" className="whitespace-nowrap font-semibold text-[#006b3c]">Dashboard</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Transfers</Link><Link href="/procurement" className="whitespace-nowrap font-semibold text-[#006b3c] hover:text-[#005b33]">Procurement</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Approvals</Link><Link href="/mediatrix" className="whitespace-nowrap hover:text-[#006b3c]">Mediatrix</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Bello Foods</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Retirement</Link><Link href="/transfers" className="whitespace-nowrap hover:text-[#006b3c]">Reports</Link><div className="ml-auto whitespace-nowrap"><form action={logout}><button type="submit" className="font-semibold text-red-700 hover:text-red-900">Sign out</button></form></div>
  </div></nav>
  <section className="mx-auto max-w-7xl px-6 py-8 md:px-8">
   <div className="mb-8 flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="mb-1 text-sm font-semibold uppercase tracking-wider text-[#006b3c]">Finance &amp; Disbursement</p><h2 className="text-3xl font-bold">Transfer Control Dashboard</h2><p className="mt-2 text-sm text-gray-500">Authorize, procure, transfer, certify, retire and reconcile ZARIKS funds.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/procurement/new" className="inline-flex items-center justify-center rounded-lg border-2 border-[#006b3c] bg-white px-6 py-3 font-bold text-[#006b3c] shadow-sm">+ New Procurement Request</Link><Link href="/transfers/new" className="inline-flex items-center justify-center rounded-lg bg-[#FDB515] px-6 py-3 font-bold text-[#172016] shadow-sm">+ New Fund Transfer</Link></div></div>
   <div className="mb-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total Transfers" value={String(initialTransfers.length)}/><Metric label="Value Processed" value={money(total)}/><Metric label="Pending Actions" value={String(pending)}/><Metric label="Closed / Certified" value={String(certified)}/></div>
   <div className="mb-8 rounded-xl border-2 border-[#d8c77a] bg-[#fffdf5] p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-wider text-[#006b3c]">Cashflow &amp; Procurement</p><h3 className="mt-1 text-xl font-bold">Money / Procurement Requests</h3><p className="mt-1 max-w-2xl text-sm text-gray-600">Create procurement and money requests, add line items and costs, then route them through verification, finance review and final approval.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-green-100 px-3 py-1">1 Request</span><span className="rounded-full bg-green-100 px-3 py-1">2 Verify</span><span className="rounded-full bg-green-100 px-3 py-1">3 Finance Review</span><span className="rounded-full bg-green-100 px-3 py-1">4 Final Approval</span></div></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row"><Link href="/procurement" className="rounded-lg border border-[#006b3c] px-5 py-3 text-center font-bold text-[#006b3c]">View Requests</Link><Link href="/procurement/new" className="rounded-lg bg-[#006b3c] px-5 py-3 text-center font-bold text-white">Create Request</Link></div></div></div>
   <div className="mb-8 rounded-xl border bg-white p-6 shadow-sm"><div className="mb-5"><h3 className="text-lg font-bold">ZARI Transfer Flow</h3><p className="text-sm text-gray-500">Controlled movement of funds and accountability.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><WorkflowStep number="1" label="Request"/><WorkflowStep number="2" label="Approve"/><WorkflowStep number="3" label="Transfer"/><WorkflowStep number="4" label="Mediatrix Receipt"/><WorkflowStep number="5" label="Bello Certification"/><WorkflowStep number="6" label="Retire & Close"/></div></div>
   <div className="mb-8 grid gap-5 md:grid-cols-4"><QuickAction title="Procurement" description="Create and track money or procurement requests." href="/procurement" action="Open procurement →"/><QuickAction title="Create Transfer" description="Create a new auditable request for funds." href="/transfers/new" action="Create request →"/><QuickAction title="View Transfers" description="Review transfer requests, approvals and payment status." href="/transfers" action="Open transfers →"/><QuickAction title="Recipient Confirmation" description="Review payments awaiting Mediatrix receipt confirmation." href="/mediatrix" action="Open Mediatrix →"/></div>
   <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-5"><div><h3 className="font-bold">Recent Fund Transfers</h3><p className="text-sm text-gray-500">Current transfer and certification records.</p></div><Link href="/transfers" className="text-sm font-semibold text-[#006b3c]">View all →</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-6 py-4">Transaction</th><th className="px-6 py-4">Recipient</th><th className="px-6 py-4">Purpose</th><th className="px-6 py-4">Amount</th><th className="px-6 py-4">Date</th><th className="px-6 py-4">Status</th></tr></thead><tbody>{initialTransfers.map(t=><tr key={t.id} className="border-t hover:bg-gray-50"><td className="px-6 py-5"><Link href="/transfers" className="font-semibold text-[#006b3c]">{t.id}</Link></td><td className="px-6 py-5">{t.recipient}</td><td className="px-6 py-5">{t.purpose}</td><td className="px-6 py-5 font-semibold">{money(t.amount)}</td><td className="px-6 py-5">{t.date}</td><td className="px-6 py-5"><StatusBadge status={t.status}/></td></tr>)}</tbody></table></div></div>
  </section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function WorkflowStep({number,label}:{number:string;label:string}){return <div className="rounded-lg border border-green-100 bg-green-50 p-4"><div className="mb-3 flex h-8 w-8 items-center justify-center rounded-full bg-[#006b3c] text-xs font-bold text-white">{number}</div><p className="text-sm font-semibold">{label}</p></div>}
function QuickAction({title,description,href,action}:{title:string;description:string;href:string;action:string}){return <div className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm text-gray-500">{description}</p><Link href={href} className="mt-4 inline-block text-sm font-semibold text-[#006b3c]">{action}</Link></div>}
function StatusBadge({status}:{status:string}){let c="bg-gray-100 text-gray-700";if(status==="Certified")c="bg-green-100 text-green-700";if(status==="Awaiting Receipt")c="bg-yellow-100 text-yellow-800";if(status==="Approved")c="bg-blue-100 text-blue-700";if(status==="Submitted")c="bg-purple-100 text-purple-700";return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${c}`}>{status}</span>}
