"use client";
import { useMemo,useState } from "react";
import { createProcurementRequest } from "@/app/actions/procurement";
type Line={id:number;item:string;description:string;quantity:number;unit:string;unitCost:number};
const blank=(id:number):Line=>({id,item:"",description:"",quantity:1,unit:"",unitCost:0});
const ngn=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",minimumFractionDigits:2});
export default function ProcurementRequestForm(){
 const[lines,setLines]=useState<Line[]>([blank(1)]); const[recurring,setRecurring]=useState(false);
 const total=useMemo(()=>lines.reduce((s,l)=>s+(Number(l.quantity)||0)*(Number(l.unitCost)||0),0),[lines]);
 const update=(id:number,p:Partial<Line>)=>setLines(c=>c.map(l=>l.id===id?{...l,...p}:l));
 return <form action={createProcurementRequest} className="space-y-8">
  <section className="rounded-xl border border-green-100 bg-green-50 p-4"><p className="font-semibold text-[#006b3c]">Who can submit?</p><p className="mt-1 text-sm text-gray-600">Any active ZARIKS team member can submit a financial request. The system records the signed-in user as the requester automatically.</p></section>
  <section className="grid gap-5 md:grid-cols-2">
   <Field label="Request Type"><select name="request_type" className="input" defaultValue="procurement"><option value="procurement">Procurement / Purchase</option><option value="money_request">General Money Request</option><option value="salary">Salary / Payroll</option><option value="commission">Commission</option><option value="bonus">Bonus / Incentive</option><option value="allowance">Allowance</option><option value="reimbursement">Reimbursement</option><option value="petty_cash">Petty Cash</option><option value="vendor_payment">Vendor / Service Payment</option><option value="other">Other Financial Request</option></select></Field>
   <Field label="Request Date"><input name="request_date" type="date" className="input" defaultValue={new Date().toISOString().slice(0,10)} required/></Field>
   <Field label="Requested From"><input name="from_whom" className="input" placeholder="Department, budget or funding source"/></Field><Field label="Payee / Recipient"><input name="to_whom" className="input" placeholder="Employee, supplier, contractor or recipient"/></Field><Field label="Department / Cost Centre"><input name="department" className="input" placeholder="e.g. Production, Sales, Administration"/></Field><Field label="Required / Payment Date"><input name="required_by" type="date" className="input"/></Field>
  </section>
  <section className="rounded-xl border p-5"><div className="grid gap-5 md:grid-cols-2"><Field label="Payment Nature"><select name="payment_nature" className="input" value={recurring?"recurring":"one_time"} onChange={e=>setRecurring(e.target.value==="recurring")}><option value="one_time">One-time payment</option><option value="recurring">Recurring / scheduled payment</option></select></Field>{recurring&&<Field label="Frequency"><select name="recurrence_frequency" className="input" required><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="biweekly">Every two weeks</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="custom">Custom</option></select></Field>}{recurring&&<Field label="Schedule Start"><input name="schedule_start_date" type="date" className="input" required/></Field>}{recurring&&<Field label="Schedule End (optional)"><input name="schedule_end_date" type="date" className="input"/></Field>}</div>{recurring&&<p className="mt-4 text-sm text-gray-500">The schedule is not activated until it completes verification, finance review and final approval.</p>}</section>
  <section><Field label="Purpose"><input name="purpose" className="input" placeholder="State exactly what this payment or procurement is for" required/></Field><div className="mt-5"><Field label="Justification / Notes"><textarea name="justification" className="input min-h-28" placeholder="Explain the basis for this request, payment, commission, bonus or procurement"/></Field></div></section>
  <section><div className="mb-4 flex items-center justify-between gap-4"><div><h2 className="text-lg font-bold">Payment / Cost Items</h2><p className="text-sm text-gray-500">For payroll, commission or bonus, enter each payable line. For procurement, enter each item being purchased. All values are in Nigerian Naira (₦).</p></div><button type="button" onClick={()=>setLines(v=>[...v,blank(Date.now())])} className="rounded-lg border border-[#006b3c] px-4 py-2 text-sm font-bold text-[#006b3c]">+ Add Line</button></div><div className="space-y-4">{lines.map((l,i)=><div key={l.id} className="rounded-xl border bg-[#fbfcfa] p-4"><div className="mb-3 flex justify-between"><strong>Line {i+1}</strong>{lines.length>1&&<button type="button" className="text-sm font-semibold text-red-700" onClick={()=>setLines(v=>v.filter(x=>x.id!==l.id))}>Remove</button>}</div><div className="grid gap-4 md:grid-cols-6"><div className="md:col-span-2"><Field label="Item / Pay Component"><input name="item_name" value={l.item} onChange={e=>update(l.id,{item:e.target.value})} className="input" placeholder="e.g. Salary, commission, bottles" required/></Field></div><div className="md:col-span-2"><Field label="Description"><input name="item_description" value={l.description} onChange={e=>update(l.id,{description:e.target.value})} className="input"/></Field></div><Field label="Qty"><input name="quantity" type="number" min="0.01" step="0.01" value={l.quantity} onChange={e=>update(l.id,{quantity:Number(e.target.value)})} className="input" required/></Field><Field label="Unit"><input name="unit" value={l.unit} onChange={e=>update(l.id,{unit:e.target.value})} className="input" placeholder="month, pcs, %..."/></Field><div className="md:col-span-2"><Field label="Rate / Unit Cost (₦)"><input name="unit_cost" type="number" min="0" step="0.01" value={l.unitCost} onChange={e=>update(l.id,{unitCost:Number(e.target.value)})} className="input" required/></Field></div><div className="md:col-span-2"><p className="text-sm font-semibold text-gray-600">Line Total</p><p className="mt-2 text-lg font-bold">{ngn.format(l.quantity*l.unitCost)}</p></div></div></div>)}</div></section>
  <section className="rounded-xl bg-[#063d28] p-6 text-white"><div className="flex items-end justify-between"><div><p className="text-sm text-green-100">TOTAL REQUESTED</p><p className="text-xs text-green-100">Currency: NGN</p></div><p className="text-3xl font-bold text-[#FDB515]">{ngn.format(total)}</p></div></section>
  <section className="rounded-xl border p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#006b3c]">Approval workflow</p><p className="mt-2 text-sm text-gray-600">After submission, ZARIKS routes the request through Verification → Finance Review → Final Approval. Names and action owners are shown on the request record only when relevant, not on this submission form.</p></section>
  <div className="flex justify-end"><button type="submit" className="rounded-lg bg-[#FDB515] px-7 py-3 font-bold text-[#172016] shadow-sm">Submit Request</button></div>
 </form>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-gray-700">{label}</span>{children}</label>}
