"use client";
import {useState} from "react";import {createClient} from "@/lib/supabase";
type O={id:string;request_no:string;approved_amount:number;currency:string;purpose:string;beneficiary:string|null;status:string;disbursed_amount:number;accepted_receipts:number;returned_cash:number};
type R={id:string;transfer_id:string;approved_obligation_id:string|null;receipt_number:string|null;vendor_name:string;purchase_date:string;amount:number;description:string;file_name:string;storage_path:string;status:string;review_notes:string|null;created_at:string};
type T={id:string;transaction_no:string;approved_obligation_id:string|null;amount_transferred:number|null};
type C={id:string;approved_obligation_id:string;amount:number;reference:string|null;returned_at:string};
const money=(v:number)=>"₦"+Number(v||0).toLocaleString("en-NG",{minimumFractionDigits:0,maximumFractionDigits:2});
export default function ReceiptReconciliation({obligations,receipts,returns,transfers,canReview}:{obligations:O[];receipts:R[];returns:C[];transfers:T[];canReview:boolean}){
 const [busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function review(id:string,decision:"accepted"|"returned"){let notes="";if(decision==="returned"){notes=window.prompt("Reason for correction / return:")?.trim()||"";if(!notes)return}setBusy(id);setMsg("");const {error}=await createClient().rpc("review_expense_receipt",{p_receipt_id:id,p_decision:decision,p_notes:notes||null});if(error){setMsg(error.message);setBusy("");return}window.location.reload()}
 async function evidence(path:string){const {data,error}=await createClient().storage.from("transfer-evidence").createSignedUrl(path,300);if(error||!data?.signedUrl){setMsg(error?.message||"Unable to open evidence.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function cashReturn(o:O){const raw=window.prompt("Amount of cash returned:");if(!raw)return;const amount=Number(raw.replace(/,/g,""));if(!amount||amount<=0)return;const ref=window.prompt("Return/payment reference (optional):")||"";const t=transfers.find(x=>x.approved_obligation_id===o.id);setBusy(o.id);const {error}=await createClient().rpc("record_cash_return",{p_obligation_id:o.id,p_transfer_id:t?.id||null,p_amount:amount,p_reference:ref||null,p_notes:null});if(error){setMsg(error.message);setBusy("");return}window.location.reload()}
 async function reconcile(o:O){setBusy(o.id);setMsg("");const {error}=await createClient().rpc("reconcile_approved_obligation",{p_obligation_id:o.id});if(error){setMsg(error.message);setBusy("");return}window.location.reload()}
 return <div className="space-y-5">{msg&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{msg}</div>}
  <section className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-bold">Approved Money Accountability</h2><p className="mt-1 text-sm text-gray-500">Approved → Disbursed → Accepted receipts → Returned cash → Outstanding.</p></div></div>
  {!obligations.length?<p className="mt-5 text-sm text-gray-500">No finally approved obligations yet. They will appear here automatically after Final Approval.</p>:<div className="mt-5 space-y-4">{obligations.map(o=>{const outstanding=Math.max(0,Number(o.disbursed_amount)-Number(o.accepted_receipts)-Number(o.returned_cash));const pending=receipts.filter(r=>r.approved_obligation_id===o.id&&["submitted","under_review"].includes(r.status)).length;return <article key={o.id} className="rounded-xl border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wide text-[#006b3c]">{o.request_no}</div><h3 className="mt-1 font-bold">{o.purpose}</h3><p className="text-xs text-gray-500">{o.beneficiary||"No beneficiary recorded"} · {o.status.replaceAll("_"," ")}</p></div>{o.status==="reconciled"&&<span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-800">RECONCILED</span>}</div>
  <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5"><Metric label="Approved" value={money(o.approved_amount)}/><Metric label="Disbursed" value={money(o.disbursed_amount)}/><Metric label="Accepted receipts" value={money(o.accepted_receipts)}/><Metric label="Returned cash" value={money(o.returned_cash)}/><Metric label="Outstanding" value={money(outstanding)} strong={outstanding>0}/></div>
  {canReview&&o.status!=="reconciled"&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>cashReturn(o)} disabled={busy===o.id} className="rounded-lg border border-[#006b3c] px-4 py-2 text-sm font-bold text-[#006b3c]">Record returned cash</button><button onClick={()=>reconcile(o)} disabled={busy===o.id||outstanding>0||pending>0||Number(o.disbursed_amount)<=0} className="rounded-lg bg-[#006b3c] px-4 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Reconcile & close accountability</button>{(outstanding>0||pending>0)&&<span className="self-center text-xs text-gray-500">{pending>0?pending+" receipt(s) awaiting review. ":""}{outstanding>0?money(outstanding)+" still unaccounted for.":""}</span>}</div>}
 </article>})}</div>}</section>
  <section className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Receipt Review Queue</h2><p className="mt-1 text-sm text-gray-500">Uploaders cannot certify their own spending. Authorized Finance reviewers accept evidence or return it for correction.</p>
  {!receipts.length?<p className="mt-5 text-sm text-gray-500">No receipts uploaded yet.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Date</th><th className="p-3">Vendor</th><th className="p-3">Amount</th><th className="p-3">Evidence</th><th className="p-3">Status</th><th className="p-3">Review</th></tr></thead><tbody>{receipts.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.purchase_date}</td><td className="p-3"><b>{r.vendor_name}</b><div className="text-xs text-gray-500">{r.receipt_number||"No receipt number"}</div></td><td className="p-3 font-bold">{money(r.amount)}</td><td className="p-3"><button onClick={()=>evidence(r.storage_path)} className="font-semibold text-[#006b3c] underline">{r.file_name}</button></td><td className="p-3"><span className="capitalize">{r.status.replaceAll("_"," ")}</span>{r.review_notes&&<div className="max-w-xs text-xs text-red-700">{r.review_notes}</div>}</td><td className="p-3">{canReview&&r.status!=="accepted"?<div className="flex gap-2"><button disabled={busy===r.id} onClick={()=>review(r.id,"accepted")} className="rounded bg-[#006b3c] px-3 py-2 text-xs font-bold text-white">Accept</button><button disabled={busy===r.id} onClick={()=>review(r.id,"returned")} className="rounded border border-red-300 px-3 py-2 text-xs font-bold text-red-700">Return for correction</button></div>:<span className="text-xs text-gray-400">—</span>}</td></tr>)}</tbody></table></div>}</section>
 </div>}
}
function Metric({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={"rounded-lg border p-3 "+(strong?"border-amber-300 bg-amber-50":"bg-gray-50")}><div className="text-xs text-gray-500">{label}</div><div className="mt-1 font-bold">{value}</div></div>}
