"use client";
import {FormEvent,useState} from "react"; import {createClient} from "@/lib/supabase";
type Transfer={id:string;transaction_no:string;description:string;payee_name:string|null;amount_transferred:number|null;status:string;supported:number};
export default function ReceiptUploadForm({transfers}:{transfers:Transfer[]}){
 const [loading,setLoading]=useState(false),[message,setMessage]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const f=new FormData(e.currentTarget),transferId=String(f.get("transfer_id")||""),file=f.get("file") as File;
 if(!transferId||!file?.size){setMessage("Select a disbursed transaction and receipt file.");setLoading(false);return}
 if(file.size>10485760){setMessage("Receipt file must be 10 MB or smaller.");setLoading(false);return}
 if(!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type)){setMessage("Upload a PDF, JPG, PNG or WebP receipt.");setLoading(false);return}
 const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Your session has expired.");setLoading(false);return}
 const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=transferId+"/receipts/"+Date.now()+"-"+safe;
 const up=await supabase.storage.from("transfer-evidence").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(up.error.message);setLoading(false);return}
 const ins=await supabase.from("expense_receipts").insert({transfer_id:transferId,receipt_number:String(f.get("receipt_number")||"").trim()||null,vendor_name:String(f.get("vendor_name")||"").trim(),purchase_date:String(f.get("purchase_date")||""),amount:Number(f.get("amount")),category:String(f.get("category")||"other"),description:String(f.get("description")||"").trim(),file_name:file.name,storage_path:path,uploaded_by:user.id,status:"submitted"});
 if(ins.error){setMessage(ins.error.message);setLoading(false);return} window.location.reload();}
 return <form onSubmit={submit} className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Upload receipt / expense evidence</h2><p className="mt-1 text-sm text-gray-500">The person who received or spent the funds uploads the evidence. PDF/JPG/PNG/WebP, maximum 10 MB.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="mb-1 block text-sm font-semibold">Linked disbursement</span><select name="transfer_id" required className="w-full rounded-lg border p-3"><option value="">Select transaction</option>{transfers.map(t=><option key={t.id} value={t.id}>{t.transaction_no+" — "+t.description+" — Disbursed ₦"+Number(t.amount_transferred||0).toLocaleString()+" — Supported ₦"+t.supported.toLocaleString()}</option>)}</select></label><label><span className="mb-1 block text-sm font-semibold">Vendor / payee</span><input name="vendor_name" required className="w-full rounded-lg border p-3"/></label><label><span className="mb-1 block text-sm font-semibold">Receipt number (optional)</span><input name="receipt_number" className="w-full rounded-lg border p-3"/></label><label><span className="mb-1 block text-sm font-semibold">Purchase date</span><input name="purchase_date" type="date" required className="w-full rounded-lg border p-3"/></label><label><span className="mb-1 block text-sm font-semibold">Amount spent</span><input name="amount" type="number" min="0.01" step="0.01" required className="w-full rounded-lg border p-3"/></label><label><span className="mb-1 block text-sm font-semibold">Category</span><select name="category" className="w-full rounded-lg border p-3"><option value="procurement">Procurement</option><option value="transport">Transport</option><option value="operations">Operations</option><option value="services">Services</option><option value="other">Other</option></select></label><label><span className="mb-1 block text-sm font-semibold">Receipt / evidence file</span><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required className="w-full rounded-lg border p-3"/></label><label className="md:col-span-2"><span className="mb-1 block text-sm font-semibold">What was purchased / paid for?</span><textarea name="description" required rows={3} className="w-full rounded-lg border p-3"/></label></div>{message&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{message}</p>}<button disabled={loading} className="mt-5 rounded-lg bg-[#006b3c] px-6 py-3 font-bold text-white disabled:opacity-60">{loading?"Uploading...":"Upload receipt"}</button></form>
}