import Link from "next/link";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase-server";
import { generateScheduledPayment } from "@/app/actions/payroll";

const money = (n:number|string|null) => new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:2}).format(Number(n??0));
const date = (d:string|null) => d ? new Intl.DateTimeFormat("en-NG",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${d}T12:00:00`)) : "—";
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default async function PayrollPage(){
 const supabase=await createServerSupabaseClient();
 const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:member}=await supabase.from("procurement_members").select("workflow_role,active").eq("user_id",user.id).maybeSingle();
 const canGenerate=member?.active && ["finance_officer","final_approver"].includes(member.workflow_role);
 const today=new Date(); const todayIso=today.toISOString().slice(0,10); const week=new Date(today); week.setDate(week.getDate()+7); const weekIso=week.toISOString().slice(0,10); const monthEnd=new Date(today.getFullYear(),today.getMonth()+1,0).toISOString().slice(0,10);
 const {data:schedules,error}=await supabase.from("payment_schedules").select("id,source_request_id,request_type,payee,purpose,amount,frequency,start_date,end_date,next_due_date,status,approved_at").order("next_due_date",{ascending:true});
 if(error) throw new Error(error.message);
 const rows=schedules??[]; const active=rows.filter(s=>s.status==="active"); const dueWeek=active.filter(s=>s.next_due_date<=weekIso); const dueMonth=active.filter(s=>s.next_due_date<=monthEnd); const overdue=active.filter(s=>s.next_due_date<todayIso); const monthValue=dueMonth.reduce((a,s)=>a+Number(s.amount),0);
 const {data:runs}=await supabase.from("scheduled_payment_runs").select("id,schedule_id,due_date,amount,payee,purpose,status,transfer_id,generated_at").order("generated_at",{ascending:false}).limit(20);
 return <main className="min-h-screen bg-[#f5f7f5] text-[#152019]"><div className="mx-auto max-w-7xl px-6 py-8 md:px-8">
  <div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><Link href="/" className="text-sm font-semibold text-[#006b3c]">← Dashboard</Link><p className="mt-5 text-sm font-bold uppercase tracking-wider text-[#006b3c]">Finance Operations</p><h1 className="mt-1 text-3xl font-bold">Payroll &amp; Scheduled Payments</h1><p className="mt-2 max-w-3xl text-sm text-gray-600">Approved recurring salaries, commissions, allowances and other scheduled obligations. Generate the next due payment here; the payment then enters ZARIKS Payments &amp; Transfers for actual disbursement.</p></div><Link href="/procurement/new" className="rounded-lg bg-[#006b3c] px-5 py-3 text-center font-bold text-white">+ New Salary / Scheduled Request</Link></div>
  <section className="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active Schedules" value={String(active.length)}/><Metric label="Due in Next 7 Days" value={String(dueWeek.length)}/><Metric label="Due This Month" value={money(monthValue)}/><Metric label="Overdue" value={String(overdue.length)} danger={overdue.length>0}/></section>
  <section className="mb-7 rounded-xl border bg-white shadow-sm"><div className="border-b px-6 py-5"><h2 className="text-lg font-bold">Upcoming &amp; Due Payments</h2><p className="mt-1 text-sm text-gray-500">One approved schedule creates one payment per due date. Duplicate generation is blocked.</p></div>{active.length===0?<Empty text="No active payroll or recurring payment schedules yet. Create a recurring financial request and complete final approval first."/>:<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[#f8faf8] text-xs uppercase text-gray-500"><tr><Th>Due</Th><Th>Type</Th><Th>Payee</Th><Th>Purpose</Th><Th>Frequency</Th><Th>Amount</Th><Th>Status</Th><Th>Action</Th></tr></thead><tbody>{active.map(s=>{const isOver=s.next_due_date<todayIso;return <tr key={s.id} className="border-t"><Td><span className={isOver?"font-bold text-red-700":"font-semibold"}>{date(s.next_due_date)}</span></Td><Td>{label(s.request_type)}</Td><Td>{s.payee||"—"}</Td><Td>{s.purpose}</Td><Td>{label(s.frequency)}</Td><Td><strong>{money(s.amount)}</strong></Td><Td><span className={`rounded-full px-3 py-1 text-xs font-semibold ${isOver?"bg-red-100 text-red-800":"bg-green-100 text-green-800"}`}>{isOver?"Overdue":"Active"}</span></Td><Td>{canGenerate?<form action={generateScheduledPayment}><input type="hidden" name="schedule_id" value={s.id}/><button className="rounded-lg bg-[#FDB515] px-4 py-2 font-bold text-[#172016]">Generate Payment</button></form>:<span className="text-xs text-gray-500">Finance action</span>}</Td></tr>})}</tbody></table></div>}</section>
  <section className="rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-5"><div><h2 className="text-lg font-bold">Generated Scheduled Payments</h2><p className="mt-1 text-sm text-gray-500">Audit trail of payment records created from approved schedules.</p></div><Link href="/transfers" className="text-sm font-semibold text-[#006b3c]">Payments &amp; Transfers →</Link></div>{!runs?.length?<Empty text="No scheduled payments have been generated yet."/>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f8faf8] text-xs uppercase text-gray-500"><tr><Th>Due Date</Th><Th>Payee</Th><Th>Purpose</Th><Th>Amount</Th><Th>Run Status</Th><Th>Payment</Th></tr></thead><tbody>{runs.map(r=><tr key={r.id} className="border-t"><Td>{date(r.due_date)}</Td><Td>{r.payee||"—"}</Td><Td>{r.purpose}</Td><Td><strong>{money(r.amount)}</strong></Td><Td>{label(r.status)}</Td><Td>{r.transfer_id?<Link className="font-semibold text-[#006b3c]" href={`/transfers/${r.transfer_id}`}>Open payment →</Link>:"—"}</Td></tr>)}</tbody></table></div>}</section>
 </div></main>
}
function Metric({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-gray-500">{label}</p><p className={`mt-2 text-2xl font-bold ${danger?"text-red-700":""}`}>{value}</p></div>}
function Th({children}:{children:React.ReactNode}){return <th className="px-5 py-3 font-semibold">{children}</th>}
function Td({children}:{children:React.ReactNode}){return <td className="px-5 py-4 align-top">{children}</td>}
function Empty({text}:{text:string}){return <div className="px-6 py-10 text-center text-sm text-gray-500">{text}</div>}
